### ISSUE TITLE
Additional fields in yml files

### ISSUE THREAD

**Issue by tnaumann** [rycolab/aclpub2#104]
Will supplying additional fields in yml files cause unintended effects? Specifically, I would like to know whether adding a `homepage` field in `organizing_committee.yml` will create problems. E.g.,

```
- role: General Chairs
  members:
  - first_name: Tristan
    last_name: Naumann
    institution: Microsoft Research
    homepage: https://aka.ms/tristan
  ...
```

This is specifically so that we can use the same yml file as a `_data` file for Jekyll because it would be pretty cool if the same yml files could be used both for website and proceedings!
