### ISSUE TITLE
Attachments Inconsistency

### ISSUE THREAD

**Issue by xinru1414** [rycolab/aclpub2#111]
Two problems: 
- Naming convention: 

  - for acl 2022, I've seen attachments named as `papernumber.zip` in the `attachments` folder, e.g. `1.zip` ; however in the `papers.yaml` file they are named as `papernumber_zip` , e.g, `1_zip`. 
  - for naacl 2022, I've seen the attachments named as `papernumber_LaTeXSource.zip` or `papernumber_OptionalSupplementaryMaterial.zip` or `papernumber_LaTeXSource.tex` in the `attachments` folder, e.g. `40_LaTeXSource.tex` and `40_OptionalSupplementaryMaterial.zip`. Some papers have both `papernumber_OptionalSupplementaryMaterial.zip` and `papernumber_LaTeXSource.zip` as the attachments with  Supplementary Material as their type (I wonder if this is a mistake)
 
- Attachment type:
  - for acl 2022, attachments (normally end in .zip) have type `software` in the papers.yaml file; however for naacl 2022, attachments have type `Supplementary Material` for zip file and tex file.

**Comment by crux82** [comment]
Hi @xinru1414 

I try to clarify this point. 

All files should have the classical format: `filename.fileextension`.
During ACL the exporting script had a bug so it exported the files as `filename_fileextension`
This bug is now fixed and (I really hope) you should do not receive any file in the `filename_fileextension`.

Regarding the second point.
The instructions at https://github.com/rycolab/aclpub2#papersyml specify that the format should be:

````
  attachments:
    # A list of additional files associated with the paper.
    # The type, along with one of file must be specified.
    - type: dataset | note | poster | presentation | software | attachment
      file: Local file path, e.g. attachments/5.zip
````
Unfortunately the organizers of that workshop were not aware of it. 
Moroever, they were exporting the files from softconf and they believed they need to send also the latex source material. 
I told them not to upload any source in latex and they should solved the problem of the type. 

Obviously, feel free to suggest any possible way to improve our documentation. 
It was not simple to foresee all possible cases and maybe we were not clear enough.
