### ISSUE TITLE
Documentation: papers need to be marked archival

### ISSUE THREAD

**Issue by evanmiltenburg** [rycolab/aclpub2#134]
I just got stuck compiling proceedings with manually written YAML files. Apparently it is required to have a key `archival` that is set to `true` in the `papers.yml` file. Otherwise aclpub yields a LaTeX error asking whether there is perhaps a missing item in my list (i.e. the list of papers) because the `\begin{itemize}...\end{itemise}` environment is empty.

**Comment by ryancotterell** [comment]
This is required to prevent people from adding non-archival papers to the Anthology, which requires a headache. What would you recommend?

**Comment by evanmiltenburg** [comment]
You could either add a note to `README.md` (under the header **papers.yml**) saying something like:

> Also note that all archival papers require a field called `archival` with the value set to `true`. Papers lacking this information will not appear in the proceedings.

Or you could edit the example to read:

```yaml
- id: Unique ID for the paper.
  authors:  # List of authors, structure detailed below.
    - first_name: First name e.g. Jane
      middle_name: (opt) Middle name e.g. Emily
      last_name: Last name e.g. Doe
      preferred_name: (opt) Prefered name, if not the same as first_name.
      institution: Name of the author's institution.
      email: Author's email.
      openreview: (opt) Author's OpenReview username.
      google_scholar: (opt) Author's Google Scholar ID.
      orcid: (opt) Author's ORCID ID.
      dblp: (opt) Author's DBLP ID.
      semantic_scholar: (opt) Author's Semantic Scholar ID.
  attributes:
    # Key-value pairs used to manage other aspects of
    # the publication process. Below are examples of possible
    # attributes. These attributes are not shown in the proceedings ... 
    # but these are really useful in other steps, e.g., in the 
    # definition of the program.
    paper_type: long | short
    presentation_type: oral | poster
    submitted_area: Semantics | Machine Learning | ...
  file: File name relative to the papers/ directory, e.g. 1.pdf
  attachments:
    # A list of additional files associated with the paper.
    # The type, along with one of file must be specified.
    - type: dataset | note | poster | presentation | software | attachment
      file: Local file path, e.g. attachments/5.zip
  title: Title of the paper.
  abstract: Abstract of the paper, usually a LaTeX fragment.
  # Papers without this information will be left out of the proceedings:
  archival: true
```
