### ISSUE TITLE
Some modifications in the conference_details.yml for the publication in ACL anthology

### ISSUE THREAD

**Issue by crux82** [rycolab/aclpub2#33]
@zhzhang: for the publication in the ACL anthology, the `conference_details.yml` file should contain the following fields:

- `editors`: the list of the volume editors (i.e., the Program Chairs in the main conference and the Workshop Organizers in the workshop). It should be a list of entities with name/family name/middle name as the authors of the papers.
- the `address` of the conference: it should be a string

@mjpost: is it correct? are we missing anything?

**Comment by mjpost** [comment]
If you're referring to [this example](https://github.com/rycolab/aclpub2/blob/main/examples/sigdial/conference_details.yml). Please see my notes [here on this Wiki page](https://github.com/rycolab/aclpub2/wiki/Anthology-ingestion-format) for more information about what I think is missing.

**Comment by crux82** [comment]
What do you think about this for a conference like ACL (that is composed of several volumes)?

```yaml
name: The 60th Annual Meeting of the Association for Computational Linguistics
volume: Proceedings of the Conference, Vol. 1 (Long Papers)
abbreviation: ACL2022
start_date: 2022-05-22
end_date: 2020-05-22
isbn: XXX-X-XXXXXX-XX-X
addresse: Dublin
editors:
  - first_name: Smaranda
    last_name: Muresan
  - first_name: Preslav
    last_name: Nakov
  - first_name: Aline
    last_name: Villavicencio
publisher: Association for Computational Linguistics
```

The above schema is the same for all the volumes, except the field volume:
- Proceedings of the Conference (Volume 1: Long Papers) 
- Proceedings of the Conference (Volume 2: Short Papers)
- Proceedings of the Conference: Student Research Workshop
- Proceedings of the Conference: System Demonstrations
- Proceedings of the Conference: Tutorial Abstracts

Is it correct?

Thank you

**Comment by mjpost** [comment]
They have put the wrong title in the document. The title is “Proceedings of the 59th Annual Meeting of the Association for Computational Linguistics and the 11th International Joint Conference on Natural Language Processing (Volume 1: Long Papers)”.

**Comment by mjpost** [comment]
(Best to read the titles from the metadata: https://aclanthology.org/volumes/2021.acl-long/)

**Comment by crux82** [comment]
Ok, let us see if I understood.
In the following examples, I duplicated some info.
- The field `title` will be used for the metadata you require
- The fields `event` and `volume` will be used for the front matter.

@ryancotterell @zhzhang @marcopoli : do you agree?

```yaml
title: Proceedings of the 60th Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers)
event: The 60th Annual Meeting of the Association for Computational Linguistics
volume: Proceedings of the Conference (Volume 1: Long Papers)
abbreviation: ACL
start_date: 2022-05-22
end_date: 2020-05-27
isbn: XXX-X-XXXXXX-XX-X
address: Dublin
editors:
  - first_name: Smaranda
    last_name: Muresan
  - first_name: Preslav
    last_name: Nakov
  - first_name: Aline
    last_name: Villavicencio
publisher: Association for Computational Linguistics
```

and for a workshop

```yaml
title: Proceedings of the 2nd Workshop on Human Evaluation of NLP Systems (HumEval 2021)
event: The 2nd Workshop on Human Evaluation of NLP Systems
volume: Proceedings of the Workshop
abbreviation: HumEval
start_date: 2022-05-27
end_date: 2020-05-27
iisbn: XXX-X-XXXXXX-XX-X
address: Dublin
editors:
  - first_name: Belz
    last_name: Anya
  - first_name: Popović
    last_name: Maja
  - first_name: Reiter
    last_name: Ehud
  - first_name: Shimorina
    last_name: Anastasia
publisher: Association for Computational Linguistics
```

**Comment by crux82** [comment]
@mjpost : sorry to bother you. Can you confirm the above examples?

**Comment by mjpost** [comment]
I still think this is confusing. To the user, what is the difference between `title`, `event`, and `volume`? Also, `abbreviation` suggests something the organizers can just pick. Is `title` the name of the event (e.g., The 5th annual meeting of the…) or the volume of papers published at that event (in which case it is usually “Proceedings of the 5th annual). I would suggest more explicit key names, e.g., `event-name`.

It would help to know what these fields are used for in other areas.

The Anthology needs these fields. I suggest these names (`old` → `new`) to help with clarity.

* `volume` → `booktitle`: The title of the proceedings volume (often called the “book”)
* `abbreviation` → `anthology-venue-id`: Each venue has a page under its ID, e.g., https://aclanthology.org/venues/acl. This field is also used to name the papers and create the Anthology IDs, so it needs to be correct.

Incidentally, I would also rename `address` to `location`. Historically this is supposed to be used for the publisher’s address, but people use it to record where the conference was held.

**Comment by crux82** [comment]
@mjpost 

Thanks!

I see your point. 
OK, let's try again 

```yaml
title: Proceedings of the 60th Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers)
event_name: The 60th Annual Meeting of the Association for Computational Linguistics
book_title: Proceedings of the Conference (Volume 1: Long Papers)
anthology_venue_id: ACL
start_date: 2022-05-22
end_date: 2022-05-27
isbn: XXX-X-XXXXXX-XX-X
location: Dublin, Ireland
editors:
  - first_name: Smaranda
    last_name: Muresan
  - first_name: Preslav
    last_name: Nakov
  - first_name: Aline
    last_name: Villavicencio
publisher: Association for Computational Linguistics
```

and for a workshop

```yaml
title: Proceedings of the 2nd Workshop on Human Evaluation of NLP Systems (HumEval 2021)
event_name: The 2nd Workshop on Human Evaluation of NLP Systems
book_title: Proceedings of the Workshop
anthology_venue_id: HumEval
start_date: 2022-05-27
end_date: 2022-05-27
isbn: XXX-X-XXXXXX-XX-X
location: Dublin, Ireland
editors:
  - first_name: Belz
    last_name: Anya
  - first_name: Popović
    last_name: Maja
  - first_name: Reiter
    last_name: Ehud
  - first_name: Shimorina
    last_name: Anastasia
publisher: Association for Computational Linguistics
```

**Comment by mjpost** [comment]
Yes, I am suggesting you change the frontmatter to be consistent with prior years. 

You should have two names: “event-name”, which is something like “60th annual meeting of the…”, and “book-title”, which is typically “Proceedings of the {event-title}” but which may vary and so should be a separate field.

The subtitle you are using, “Proceedings of the Conference” is a stylistic approach used on the covers, where the cover is something like “{event name} (vertical whitespace) Proceedings of the Conference”. But in the metadata, we use the complete book title, which is “Proceedings of the {event-name}”.

If you want the subtitle configurable, I would give it a very specific name, something like “cover-subtitle”.

**Comment by crux82** [comment]
OK @mjpost . Hope this is the last time I bother you :-)

If you confirm the format of the conference volumes and (more critical) the workshop proceedings... I would like to ask @zhzhang to update the software. 

```book_title``` will be used by AclAnthology (so it can be ignored)
```event_name``` is the actual field ```name```
```cover_subtitle``` is the actual field ```volume```

```yaml
book_title: Proceedings of the 60th Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers)
event_name: The 60th Annual Meeting of the Association for Computational Linguistics
cover_subtitle: Proceedings of the Conference (Volume 1: Long Papers)
anthology_venue_id: ACL
start_date: 2022-05-22
end_date: 2022-05-27
isbn: XXX-X-XXXXXX-XX-X
location: Dublin, Ireland
editors:
  - first_name: Smaranda
    last_name: Muresan
  - first_name: Preslav
    last_name: Nakov
  - first_name: Aline
    last_name: Villavicencio
publisher: Association for Computational Linguistics
```

and for a workshop

```yaml
book_title: Proceedings of the 2nd Workshop on Human Evaluation of NLP Systems (HumEval 2021)
event_name: The 2nd Workshop on Human Evaluation of NLP Systems
cover_subtitle: Proceedings of the Workshop
anthology_venue_id: HumEval
start_date: 2022-05-27
end_date: 2022-05-27
isbn: XXX-X-XXXXXX-XX-X
location: Dublin, Ireland
editors:
  - first_name: Belz
    last_name: Anya
  - first_name: Popović
    last_name: Maja
  - first_name: Reiter
    last_name: Ehud
  - first_name: Shimorina
    last_name: Anastasia
publisher: Association for Computational Linguistics
```
