### ISSUE TITLE
Adding list of names/middle_name/family_name in the organizing committee or program committee section

### ISSUE THREAD

**Issue by crux82** [rycolab/aclpub2#54]
I just received the list of reviewers. But aclpub2 does not work. 

@rswilkens : reviewers should be printed grouped by names, without institutions. 
Actually aclpub2 has a specific flag `name_block` you should add for action editors and reviewers

```
- role: Reviewers
  type: name_block  # By adding the name_block type in the role, names will be output in alphabetized blocks.
  entries:
    - Committee Member Name
````

@zhzhang : however it does not work... it seems it tries to both generate the compact version and the other one
