### ISSUE TITLE
aclpub2/generate hangs up

### ISSUE THREAD

**Issue by jerbarnes** [rycolab/aclpub2#71]
Hi,

Following Danilo's advice, I updated the aclpub2 version and changed the conference_details.yml from

```
name: Workshop on Computational Approaches to Subjectivity, Sentiment \& Social Media Analysis
volume: Proceedings of the Twelfth Workshop
abbreviation: WASSA
start_date: 2022-05-26
end_date: 2022-05-26
isbn:
location: Dublin, Ireland
publisher: Association for Computational Linguistics
```

to

```
book_title: "Proceedings of the 12th Workshop on Computational Approaches to Subjectivity, Sentiment & Social Media Analysis (WASSA 2022)"
event_name: "The 12th Workshop on Computational Approaches to Subjectivity, Sentiment & Social Media Analysis"
cover_subtitle: Proceedings of the Workshop
anthology_venue_id: WASSA
start_date: 2022-05-26
end_date: 2022-05-26
isbn: XXX-X-XXXXXX-XX-X (you should replace this with the real ISBN)
location: Dublin, Ireland
editors:
  - first_name: Jeremy
    last_name: Barnes
  - first_name: Orphée
    last_name: De Clercq
  - first_name: Valentin
    last_name: Barriere
  - first_name: Shabnam
    last_name: Tafreshi
  - first_name: Sawsan
    last_name: Alqahtani
  - first_name: João
    last_name: Sedoc
  - first_name: Roman
    last_name: Klinger
  - first_name: Alexandra
    last_name: Balahur
publisher: Association for Computational Linguistics
```

However, when I run ```./bin/generate ../Wassa --proceedings --overwrite``` to generate the proceedings, the script hangs up after processing 3 papers. It doesn't give any error that I can find. Any advice?
