### ISSUE TITLE
Escaping strings in yml

### ISSUE THREAD

**Issue by tnaumann** [rycolab/aclpub2#96]
Including `&` in `program.yml` breaks the proceedings generation due to usage of a character that must be escaped in LaTeX. 

E.g., consider the following `program.yml`:

```
- title: Opening Remarks
  start_time: 2022-07-14 08:30:00
  end_time: 2022-07-14 08:40:00

- title: "Keynote"
  start_time: 2022-07-14 08:40:00
  end_time: 2022-07-14 09:25:00
  subsessions:
    - title: "Keynote Talk"
      start_time: 2022-07-14 08:40:00
      end_time: 2022-07-14 09:25:00
    - title: "Keynote Q&A"
      start_time: 2022-07-14 09:25:00
      end_time: 2022-07-14 09:40:00
```

This will currently break proceedings generation unless the `&` is escaped (i.e. `"Keynote Q\\&A"`) despite the original string "Keynote Q&A" being a valid yml string.

Two potential fixes might be:
- Escape strings that are ingested from yml 
- Document that strings appearing in yml must be escaped for downstream LaTeX

Either reduces the pain associated with hitting an error that does not provide descriptive information on how to fix and subsequent attempts to escape characters using HTML syntax (i.e. `&amp;`) which is more prevalently used in most StackOverflow answers.
